server:
  port: 13268

spring:
  application:
    name: qqserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root #请修改
    password: 123456789 #请修改
    url: jdbc:mysql://localhost:3306/yuaner?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 127.0.0.1 #请修改
    port: 6379 #请修改
    password: 123456789 #请修改
    database: 5 #请修改
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

mybatis-plus:
  type-aliases-package: com.yuaner.yuaner_community.model.entity # 别名扫描包
